// flow-typed signature: 9ec9058b3a30497f68a568b4c0096fef
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-root-import_v^0.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-root-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-root-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-root-import/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-root-import/src/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-root-import/src/index'>;
}
